### PR TITLE
fix: Use CACHE_SUFFIX env variable

### PR DESCRIPTION
**Pull request by msvticket**
This fixes that CACHE_SUFFIX wasn't read. The reason is that `envconfig.Process` wasn't called on the struct containing cacheSuffix.

The obvious solution to call `envconfig.Process(o.GetContext(), o)` in create.go failed with `WARNING: failed to default env vars: Requirements: unexpected end of JSON input`. Thus this slightly ugly fix.

I also had to do various fixes to get the code throught the linter. And while at it I added myself to the OWNERS file.

### CODE REVIEW

**Comment by ankitm123** [comment]
>I also had to do various fixes to get the code throught the linter.

Can u add the linter to the CI (else there are no checks, and things will be out of sync fast)? Check jx-secret for example.

**Comment by msvticket** [comment]
Gah!  Pending due to:

```
Warning  FailedScheduling   49s   default-scheduler   0/3 nodes are available: 3 Insufficient cpu.
Normal   NotTriggerScaleUp  48s   cluster-autoscaler  pod didn't trigger scale-up: 1 Insufficient cpu
```

**Pull request merged**
